services:
  teamstats:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - ./database.db:/app/database.db
    environment:
      TZ: America/Vancouver
      AUTH_SECRET: ${AUTH_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      BASE_URL: ${BASE_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      STRIPE_ENDPOINT_SECRET: ${STRIPE_ENDPOINT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_YEARLY_PRICE_ID: ${STRIPE_YEARLY_PRICE_ID}
      STRIPE_TEAMSTATS_PRODUCT_ID: ${STRIPE_TEAMSTATS_PRODUCT_ID}
      MIXPANEL_TOKEN: ${MIXPANEL_TOKEN}

networks:
  default:
    external: true
    name: proxy
