services:
  teamstats:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - ./database.db:/app/database.db
    environment:
      TZ: America/Vancouver
      AUTH_SECRET: ${AUTH_SECRET}

networks:
  default:
    external: true
    name: proxy
