services:
  teamstats:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - ./database.db:/app/database.db
    environment:
      TZ: America/Vancouver
      AUTH_SECRET: ${AUTH_SECRET}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      BASE_URL: ${BASE_URL}

networks:
  default:
    external: true
    name: proxy
