services:
  teamstats:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    restart: always
    volumes:
      - ./database:/app/database
    env_file:
      - .env
    environment:
      TZ: America/Vancouver

networks:
  default:
    external: true
    name: proxy
